name    'leonardothibes-wget'
author  'leonardothibes'
version '1.0.4'
license 'MIT'
summary 'A puppet module for download files with wget'
description 'A puppet module for download files with wget'
source 'git://github.com/leonardothibes/puppet-wget.git'
project_page 'http://github.com/leonardothibes/puppet-wget'
