name    'leonardothibes-env'
author  'leonardothibes'
version '1.0.2'
license 'MIT'
summary 'A puppet module to provide a Redhat shell style for Debian/Ubuntu/Mint'
description 'A puppet module to provide a Redhat shell style for Debian/Ubuntu/Mint'
source 'git://github.com/leonardothibes/puppet-env.git'
project_page 'http://github.com/leonardothibes/puppet-env'
